name: Build and Release

on:
  push:
    tags:
      - '*'  # Trigger on any tag

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for accurate changelog

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.x'

    - name: Build
      run: dotnet publish SubMerger/SubMerger.csproj -c Release -r ${{ matrix.os == 'ubuntu-latest' && 'linux-x64' || 'win-x64' }} --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -o:./output

    - name: Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ./output/SubMerger
          ./output/SubMerger.exe
        generate_release_notes: true
        make_latest: true